# https://help.github.com/en/articles/metadata-syntax-for-github-actions

name: Standalone Stats
description: Publish coverage, tests results, and other stats to gh-pages for self-contained pretty charts and badges
author: Cameron Tacklind <cameron@tacklind.com>
inputs:
  stats-branch:
    required: false
    description: Which branch folder to store the historical build stats in
    default: build-stats
  stats-repo:
    required: false
    description: Which repository to store the historical build stats in
    default: '' # Current
  pages-dir:
    required: false
    description: Which folder in the pages-branch to store the built files in
    default: action-stats
runs:
  using: 'node12'
  main: 'lib/index.js'
