name: Main

on:
  pull_request:
  push:

jobs:
  check-format:
    name: Check - Format

    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Make npm colorful
        run: echo "color = always" >> .npmrc

      - name: Build
        run: npm install

      - name: Prettier
        run: npm run format-check -- --color

  check-lint:
    name: Check - ESLint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Make npm colorful
        run: echo "color = always" >> .npmrc

      - name: Build
        run: npm install

      - name: Prettier
        run: npm run lint -- --color

  check-spelling:
    name: Check - Spelling

    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Make npm colorful
        run: echo "color = always" >> .npmrc

      - name: Build
        run: npm install

      - name: Spelling
        run: npm run spellcheck -- --color

  self-test-and-use: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Make npm colorful
        run: echo "color = always" >> .npmrc

      - name: Install Dependencies and Build
        run: npm install

      - name: Make directory for result
        run: mkdir -p public

      - name: Create trivial index page placeholder
        working-directory: public
        run: echo Hello > index.html

      - name: Tell GitHub to not use Jekyll
        working-directory: public
        run: touch .nojekyll

      - name: Create placeholder dashboard chart
        working-directory: public
        run: echo '<svg xmlns="http://www.w3.org/2000/svg" height="200" width="800"><line x1="0" y1="200" x2="800" y2="0" style="stroke:rgb(255,0,0);stroke-width:2" /></svg>' > dashboard.svg

      - name: 'Debug: List files'
        run: find * \( -path node_modules -o -path .git \) -print -prune -o -type f -print

      - uses: ./
        # This step will copy coverage reports (and others) to the specified historical branch
        # and use it to generate some pretty charts
        with:
          milliseconds: 1000
          stats-branch: build-stats
          stats-repo: '' # Current
          pages-dir: public

      # Publish to gh-pages
      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          # PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: public
        with:
          emptyCommits: false
          username: "GitHub Action Static Build"
          #useremail: "actions@github.com"

  publish:
    if: github.event_name == 'push' && github.ref == 'refs/tags/*'
    needs: [self-test-and-use, check-format, check-lint, check-spelling]
    runs-on: ubuntu-latest
    steps:
      - name: Disable WIP Publish Script
        run: "false" # WIP

      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Make npm colorful
        run: echo "color = always" >> .npmrc

      - name: Install Dependencies and Build
        run: npm install

      - name: Remove Development (and Build) Dependencies
        run: npm prune --production

      - name: Don't ignore node_modules for GitHub publish
        run: rm .gitignore

      - name: Commit built node_modules so that action is standalone
        run: git add node_modules

      - name: Create new commit with Production Dependencies
        run: 'git commit -m "Production: Include Dependencies"'

      - name: Push latest release to GitHub
        run: git push origin releases/v1 #TODO: use tag
      # https://github.com/actions/toolkit/blob/master/docs/action-versioning.md
