name: Main

on:
  pull_request:
  push:

jobs:
  check-format:
    name: Check - Format

    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Make npm colorful
        run: echo "color = always" >> .npmrc

      - name: Build
        run: npm install

      - name: Prettier
        run: npm run format-check -- --color

  check-lint:
    name: Check - ESLint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Make npm colorful
        run: echo "color = always" >> .npmrc

      - name: Build
        run: npm install

      - name: ESLint
        run: npm run lint -- --color

  check-spelling:
    name: Check - Spelling

    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Make npm colorful
        run: echo "color = always" >> .npmrc

      - name: Build
        run: npm install

      - name: Spelling
        run: npm run spellcheck -- --color

  self-test-and-use: # make sure the action works on a clean machine without building
    name: Test Coverage and Generate Reports
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Make npm colorful
        run: echo "color = always" >> .npmrc

      - name: Install Dependencies and Build
        run: npm install

        # Run Tests
      - name: Run Tests
        run: npm test -- --color

        # Generate Reports
        #
      - name: Make directory for result
        run: mkdir -p public

      - name: Temporary Placeholder Generator - index.html
        working-directory: public
        run: echo Hello > index.html

      - name: Tell GitHub to not use Jekyll
        working-directory: public
        run: touch .nojekyll

      - name: Temporary Placeholder Generator - Dashboard Chart
        run: cp banner.svg public/dashboard.svg

      - name: Generate Allure Report
        run: npm run allure

      - uses: ./
        # This step will copy coverage reports (and others) to the specified historical branch
        # and use it to generate some pretty charts
        with:
          milliseconds: 1000
          stats-branch: build-stats
          stats-repo: '' # Current
          pages-dir: public

        # DEBUG
      - name: 'Debug: List files'
        run: find * \( -path node_modules -o -path .git \) -print -prune -o -type f -print

      # Publish to gh-pages
      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: public
          github_token: ${{ secrets.GITHUB_TOKEN }}
          allow_empty_commit: false
          user_name: 'GitHub Action Static Build'
          user_email: 'actions@github.com'

  publish:
    if: github.event_name == 'push' && github.ref == 'refs/tags/*'
    needs: [self-test-and-use, check-format, check-lint, check-spelling]
    runs-on: ubuntu-latest
    steps:
      - name: Disable WIP Publish Script
        run: 'false' # WIP

      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Make npm colorful
        run: echo "color = always" >> .npmrc

      - name: Install Dependencies and Build
        run: npm install

      - name: Remove Development (and Build) Dependencies
        run: npm prune --production

      - name: Don't ignore node_modules for GitHub publish
        run: rm .gitignore

      - name: Commit built node_modules so that action is standalone
        run: git add node_modules

      - name: Create new commit with Production Dependencies
        run: 'git commit -m "Production: Include Dependencies"'

      - name: Push latest release to GitHub
        run: git push origin releases/v1 #TODO: use tag
      # https://github.com/actions/toolkit/blob/master/docs/action-versioning.md
